/* eslint-disable prettier/prettier */
export const playlist = [
  {
    id: 1,
    url: require('../assets/songs/bohemian-breeze-211821.mp3'),
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    genre: 'Rock',
    date: '1975-10-31T00:00:00+00:00',
    artwork: 'https://cdn.pixabay.com/audio/2024/01/12/04-39-23-284_200x200.jpg',
    duration: 355,
  },
  {
    id: 2,
    url: require('../assets/songs/dark-clouds-193879.mp3'),
    title: 'Imagine',
    artist: 'John Lennon',
    album: 'Imagine',
    genre: 'Soft rock',
    date: '1971-09-09T00:00:00+00:00',
    artwork: 'https://cdn.pixabay.com/audio/2024/02/29/18-57-35-496_200x200.png',
    duration: 183,
  },
  {
    id: 3,
    url: require('../assets/songs/little-prelude-for-the-luth-js-bach-179451.mp3'),
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Thriller',
    genre: 'Pop, R&B',
    date: '1983-01-02T00:00:00+00:00',
    artwork: 'https://cdn.pixabay.com/audio/2023/06/19/15-57-37-943_200x200.jpg',
    duration: 294,
  },
  {
    id: 4,
    url: require('../assets/songs/spirit-ft-vickwills-203712.mp3'),
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    genre: 'Grunge, Alternative rock',
    date: '1991-09-10T00:00:00+00:00',
    artwork: 'https://cdn.pixabay.com/audio/2024/04/21/23-27-45-938_200x200.jpg',
    duration: 301,
  },
  {
    id: 5,
    url: require('../assets/songs/california-183638.mp3'),
    title: 'Hotel California',
    artist: 'Eagles',
    album: 'Hotel California',
    genre: 'Rock',
    date: '1976-12-08T00:00:00+00:00',
    artwork: 'https://cdn.pixabay.com/audio/2023/12/31/16-29-09-439_200x200.jpg ',
    duration: 390,
  },
  // {
  //   id: 6,
  //   url: 'https://example.com/songs/like_a_rolling_stone.mp3',
  //   title: 'Like a Rolling Stone',
  //   artist: 'Bob Dylan',
  //   album: 'Highway 61 Revisited',
  //   genre: 'Folk rock',
  //   date: '1965-07-20T00:00:00+00:00',
  //   artwork: 'https://example.com/images/like_a_rolling_stone.jpg',
  //   duration: 373,
  // },
  // {
  //   id: 7,
  //   url: 'https://example.com/songs/whats_going_on.mp3',
  //   title: "What's Going On",
  //   artist: 'Marvin Gaye',
  //   album: "What's Going On",
  //   genre: 'Soul',
  //   date: '1971-05-21T00:00:00+00:00',
  //   artwork: 'https://example.com/images/whats_going_on.jpg',
  //   duration: 233,
  // },
  // {
  //   id: 8,
  //   url: 'https://example.com/songs/stairway_to_heaven.mp3',
  //   title: 'Stairway to Heaven',
  //   artist: 'Led Zeppelin',
  //   album: 'Led Zeppelin IV',
  //   genre: 'Hard rock',
  //   date: '1971-11-08T00:00:00+00:00',
  //   artwork: 'https://example.com/images/stairway_to_heaven.jpg',
  //   duration: 482,
  // },
  // {
  //   id: 9,
  //   url: 'https://example.com/songs/hey_jude.mp3',
  //   title: 'Hey Jude',
  //   artist: 'The Beatles',
  //   album: 'Hey Jude',
  //   genre: 'Rock',
  //   date: '1968-08-26T00:00:00+00:00',
  //   artwork: 'https://example.com/images/hey_jude.jpg',
  //   duration: 431,
  // },
  // {
  //   id: 10,
  //   url: 'https://example.com/songs/respect.mp3',
  //   title: 'Respect',
  //   artist: 'Aretha Franklin',
  //   album: 'I Never Loved a Man the Way I Love You',
  //   genre: 'Soul',
  //   date: '1967-04-29T00:00:00+00:00',
  //   artwork: 'https://example.com/images/respect.jpg',
  //   duration: 149,
  // },
  // {
  //   id: 11,
  //   url: 'https://example.com/songs/good_vibrations.mp3',
  //   title: 'Good Vibrations',
  //   artist: 'The Beach Boys',
  //   album: 'Smiley Smile',
  //   genre: 'Psychedelic rock',
  //   date: '1966-10-10T00:00:00+00:00',
  //   artwork: 'https://example.com/images/good_vibrations.jpg',
  //   duration: 216,
  // },
  // {
  //   id: 12,
  //   url: 'https://example.com/songs/purple_haze.mp3',
  //   title: 'Purple Haze',
  //   artist: 'The Jimi Hendrix Experience',
  //   album: 'Are You Experienced',
  //   genre: 'Psychedelic rock',
  //   date: '1967-03-17T00:00:00+00:00',
  //   artwork: 'https://example.com/images/purple_haze.jpg',
  //   duration: 170,
  // },
  // {
  //   id: 13,
  //   url: 'https://example.com/songs/blowin_in_the_wind.mp3',
  //   title: "Blowin' in the Wind",
  //   artist: 'Bob Dylan',
  //   album: "The Freewheelin' Bob Dylan",
  //   genre: 'Folk',
  //   date: '1963-05-27T00:00:00+00:00',
  //   artwork: 'https://example.com/images/blowin_in_the_wind.jpg',
  //   duration: 168,
  // },
  // {
  //   id: 14,
  //   url: 'https://example.com/songs/let_it_be.mp3',
  //   title: 'Let It Be',
  //   artist: 'The Beatles',
  //   album: 'Let It Be',
  //   genre: 'Rock',
  //   date: '1970-03-06T00:00:00+00:00',
  //   artwork: 'https://example.com/images/let_it_be.jpg',
  //   duration: 243,
  // },
  // {
  //   id: 15,
  //   url: 'https://example.com/songs/born_to_run.mp3',
  //   title: 'Born to Run',
  //   artist: 'Bruce Springsteen',
  //   album: 'Born to Run',
  //   genre: 'Rock',
  //   date: '1975-08-25T00:00:00+00:00',
  //   artwork: 'https://example.com/images/born_to_run.jpg',
  //   duration: 270,
  // },
  // {
  //   id: 16,
  //   url: 'https://example.com/songs/superstition.mp3',
  //   title: 'Superstition',
  //   artist: 'Stevie Wonder',
  //   album: 'Talking Book',
  //   genre: 'Funk, Soul',
  //   date: '1972-10-24T00:00:00+00:00',
  //   artwork: 'https://example.com/images/superstition.jpg',
  //   duration: 266,
  // },
  // {
  //   id: 17,
  //   url: 'https://example.com/songs/i_cant_get_no_satisfaction.mp3',
  //   title: "I Can't Get No Satisfaction",
  //   artist: 'The Rolling Stones',
  //   album: 'Out of Our Heads',
  //   genre: 'Rock',
  //   date: '1965-06-06T00:00:00+00:00',
  //   artwork: 'https://example.com/images/i_cant_get_no_satisfaction.jpg',
  //   duration: 225,
  // },
  // {
  //   id: 18,
  //   url: 'https://example.com/songs/comfortably_numb.mp3',
  //   title: 'Comfortably Numb',
  //   artist: 'Pink Floyd',
  //   album: 'The Wall',
  //   genre: 'Progressive rock',
  //   date: '1979-11-30T00:00:00+00:00',
  //   artwork: 'https://example.com/images/comfortably_numb.jpg',
  //   duration: 383,
  // },
  // {
  //   id: 19,
  //   url: 'https://example.com/songs/hallelujah.mp3',
  //   title: 'Hallelujah',
  //   artist: 'Leonard Cohen',
  //   album: 'Various Positions',
  //   genre: 'Folk rock',
  //   date: '1984-12-05T00:00:00+00:00',
  //   artwork: 'https://example.com/images/hallelujah.jpg',
  //   duration: 279,
  // },
  // {
  //   id: 20,
  //   url: 'https://example.com/songs/light_my_fire.mp3',
  //   title: 'Light My Fire',
  //   artist: 'The Doors',
  //   album: 'The Doors',
  //   genre: 'Psychedelic rock',
  //   date: '1967-01-04T00:00:00+00:00',
  //   artwork: 'https://example.com/images/light_my_fire.jpg',
  //   duration: 428,
  // },
  // {
  //   id: 21,
  //   url: 'http://example.com/avaritia.mp3',
  //   title: 'Avaritia',
  //   artist: 'deadmau5',
  //   album: 'while(1<2)',
  //   genre: 'Progressive House, Electro House',
  //   date: '2014-05-20T07:00:00+00:00',
  //   artwork: 'http://example.com/cover.png',
  //   duration: 402,
  // },
];

export const Artists = [
  {
    id: 1,
    name: 'Bad Guy',
    images: require('../assets/images/Music.png'),
    artist: 'Billie Eilish',
  },
  {
    id: 2,
    name: 'Scorpion',
    images: require('../assets/images/Music.png'),
    artist: 'Drake',
  },
  {
    id: 3,
    name: 'WHEN',
    images: require('../assets/images/Music.png'),
    artist: 'Billie Eilish',
  },
];

export const PlayLists = [
  {
    id: 1,
    title: 'As It Was',
    artist: 'Harry Styles',
    time: '5:33',
  },
  {
    id: 2,
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    time: '3:20',
  },
  {
    id: 3,
    title: 'Levitating',
    artist: 'Dua Lipa',
    time: '3:23',
  },
  {
    id: 4,
    title: 'Watermelon Sugar',
    artist: 'Harry Styles',
    time: '2:54',
  },
  {
    id: 5,
    title: 'Peaches',
    artist: 'Justin Bieber',
    time: ' 3:18',
  },
  {
    id: 6,
    title: 'Good 4 U',
    artist: 'Olivia Rodrigo',
    time: '2:58',
  },
  {
    id: 7,
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    time: '3:36',
  },
  {
    id: 8,
    title: 'Montero (Call Me By Your Name)',
    artist: 'Lil Nas X',
    time: ' 2:17',
  },
  {
    id: 9,
    title: 'Kiss Me More',
    artist: 'Doja Cat feat. SZA',
    time: '3:29',
  },
  {
    id: 10,
    title: 'Deja Vu',
    artist: 'Olivia Rodrigo',
    time: '3:35',
  },
  {
    id: 11,
    title: 'Industry Baby',
    artist: 'Lil Nas X & Jack Harlow',
    time: '3:32',
  },
  {
    id: 12,
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    time: '2:21',
  },
];
