name: ESLint Check

on:
  pull_request: # This ensures that the ESLint workflow runs on every pull request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust to the version of Node.js your project uses

      - name: Install dependencies
        run: npm install # Installs all dependencies, including ESLint

      - name: Run ESLint
        run: npm run lint # Executes the lint script you set in package.json
