/* eslint-disable prettier/prettier */
const images = {
  HOME_BACK: require('../assets/images/backImage.png'),
  CALL_OUTER: require('../assets/icons/callOuter.png'),
  GOOGLE: require('../assets/icons/Google.png'),
  FACEBOOK: require('../assets/icons/Facebook.png'),
  USER_FILL: require('../assets/icons/UserFill.png'),
  MENU_ICON: require('../assets/icons/menuIcon.png'),
  SEARCH_ICON: require('../assets/icons/search.png'),
  BOX_FRIEND: require('../assets/icons/boxFriend.png'),
  BOX_EXPERT: require('../assets/icons/boxExpert.png'),
  BOX_DIARIES: require('../assets/icons/boxDiaries.png'),
  BOX_MY_TRIP: require('../assets/icons/boxMyTrip.png'),
  RELATIONSHIP_ICON: require('../assets/icons/RelationshipIssues.png'),
  WALK_ICON: require('../assets/icons/LeisureWalk.png'),
  LOCATION_ICON: require('../assets/icons/location.png'),
  USERS_ICON: require('../assets/icons/users.png'),
  COINS_ICON: require('../assets/icons/coins.png'),
  MOUNTAINS: require('../assets/icons/Mountains.png'),
  TALK_ICON: require('../assets/icons/Talk.png'),
  DIARIES_ICON: require('../assets/icons/Diaries.png'),
  HUMAN_IMG: require('../assets/images/human.png'),
  NOTE_ICON: require('../assets/icons/Note.png'),
  MIC_ICON: require('../assets/icons/mic.png'),
  CALENDER_ICON: require('../assets/icons/calendar.png'),
  DOWN_ARROW: require('../assets/icons/downArrow.png'),
  EVENT_ICON:require('../assets/icons/event.png'),
  MUSIC_ICON:require('../assets/icons/music.png'),
  BOOK_ICON:require('../assets/icons/book.png'),
  OUTER_ICON:require('../assets/icons/outer.png'),
  CONNECTING_IMG: require('../assets/images/ConnectingMen.png'),
  BACK_ARROW:require('../assets/icons/back_arrow.png'),
  CONNECTED_WITH:require('../assets/images/connectedWith.png'),
  CALL_MIC:require('../assets/icons/callMic.png'),
  VIDEO_CALL:require('../assets/icons/videoCall.png'),
  CALL_MESSAGE:require('../assets/icons/callMessage.png'),
  STAR_ICON:require('../assets/icons/star.png'),
  EXPERT_IMG:require('../assets/images/expert.png'),
};
export default images;