/* eslint-disable prettier/prettier */
export const SCREENS = {
  INTRO: 'Intro',
  LOGIN: 'Login',
  REGISTER: 'Register',
  ONBOARD: 'OnBoard',
  PROFILE: 'Profile',
  NOTIFICATION: 'Notification',
  USER_DRAWER: 'UserDrawer',
  USER_HOME: 'Home',
  FELI_FRIEND: 'FeliFriend',
  FELI_EXPERT: 'FeliExpert',
  FELI_DIARIES: 'FeliDiaries',
  FREAK_MY_TRIP: 'FreakMyTrip',
  HOMESTACK: 'HomeStack',
  CONNECTING: 'Connecting',
  CONNECTED_WITH: 'ConnectedWith',
  SEARCH_EXPERT: 'SearchExpert',
  LEISURE_WALK: 'LeisureWalk',
  //Security Guard
  GUARD_TAB: 'GuardTab',
  GUARDHOME: 'Home',
  VISITOR: 'Visitor',
  ACTIVITY: 'Activity',
  SETTING: 'Setting',
  ADDVISITOR: 'AddVisitor',
  TAKEPHOTO: 'TakePhoto',

  //End User
  MYVISITOR: 'MyVisitor',
  MYBILL: 'MyBill',
  PAYMENTDEATAILS: 'PaymentDetails',
  PAYNOW: 'PayNow',
  PAYMENTMODE: 'PaymentMode',
  MYCOMPLAINTS: 'MyComplaints',
  COMPLAINTSFORM: 'ComplaintsForm',
  BOOKHALL: 'BookHall',
  COMMUNITY: 'Community',
  TODAY: 'Today',
  WEEK: 'This Week',
  MONTH: 'This Month',
  SEARCHSCREEN: 'SearchScreen',

  //President
  PRESIDENT_TAB: 'PresidentTab',
  PRESIDENTHOME: 'Home',
  COMPLAINTS: 'Complaints',
  ADDNOTICE: 'AddNotice',
  NOTICE: 'Notice',
  FINANCE: 'Finance',
  PAYMENTS: 'Payments',
  SECURITY: 'Security',
  COMPLAINDETAILS: 'ComplainDetails',
  PRESIDENT_PROFILE: 'PresidentProfile',
  RECENTVITORDETAILS: 'RecentVisitorDetails',
  NEWMEMBERDETAILS: 'NewMemberDetails',
  ANNOUNCEMENT_ALL: 'AnnouncementScreen',
};
