import { Inter, Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Headers from "./common/header/header";
import Footer from "./common/footer/page";

// const inter = Inter({ subsets: ["kumbh Sans"] });
const kumbhSans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Ceramics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <Headers />
        {children}
        <Footer /> 
      </body>
    </html>
  );
}
